# .streamlit/secrets.toml
FIRECRAWL_API_KEY = fc-640f4143df0e4be0a5762aacfe5674d9
OPENAI_API_KEY = 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
